name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x, 22.6] # Need to use 22.6 due to Next.js build errors: https://github.com/vercel/next.js/issues/69263
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    name: Build with ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    env:
      BUN_INSTALL: $HOME/.bun
      PATH: $BUN_INSTALL/bin:$PATH

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "export BUN_INSTALL=\$HOME/.bun" >> $BASH_ENV
          echo "export PATH=\$BUN_INSTALL/bin:\$PATH" >> $BASH_ENV
          source $BASH_ENV
          bun --version

      - name: Install dependencies using Bun
        run: bun install

      - name: Build the project
        run: bun run build

  test:
    strategy:
      matrix:
        node-version: [20.x]

    name: Run all tests
    runs-on: ubuntu-latest

    env:
      BUN_INSTALL: $HOME/.bun
      PATH: $BUN_INSTALL/bin:$PATH

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Retrieve Git history, needed to verify commits
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "export BUN_INSTALL=\$HOME/.bun" >> $BASH_ENV
          echo "export PATH=\$BUN_INSTALL/bin:\$PATH" >> $BASH_ENV
          source $BASH_ENV
          bun --version

      - name: Install dependencies using Bun
        run: bun install

      - if: github.event_name == 'pull_request'
        name: Validate all commits from PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Linter
        run: bun run lint

      - name: Type checking
        run: bun run check-types
